version: '3'

services:
  app:
    image: pybr2022-site
    hostname: pybr2022-site
    build: .
    volumes:
      - .:/data:z

    working_dir: /data
    ports:
      - 8081:8081
    command: bash -c "pelican content -s pelicanconf.py && cd output && python -m http.server 8081"
